service: sls-ton-api

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  region: eu-west-1
  environment:
    USERS_TABLE_NAME: ${self:custom.UsersTable.name}
    COUNT_API_URL: https://api.countapi.xyz
    NAMESPACE: ton.com.br
    KEY: visits
  iam:
    role:
      statements:
        - ${file(iam/UsersTableIAM.yml):UsersTableIAM}
  stage: ${opt:stage, 'dev'}

resources:
  Resources:
    UsersTable: ${file(resources/UsersTable.yml):UsersTable}

functions:
  createUser:
    handler: src/handlers/user/create.handler
    events:
      - http:
          method: POST
          path: /user

  getUser:
    handler: src/handlers/user/get.handler
    events:
      - http:
          method: GET
          path: /user/{id}

  getAccess:
    handler: src/handlers/access/get.handler
    events:
      - http:
          method: GET
          path: /access

  increaseAccess:
    handler: src/handlers/access/increase.handler
    events:
      - http:
          method: POST
          path: /access

custom:
  UsersTable:
    name: !Ref UsersTable
    arn: !GetAtt UsersTable.Arn